name: Build and Reease Latex PDF
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            full/full.tex
            onepage-generic/onepage.tex
            twopage-generic/twopage.tex
#          latexmk_use_xelatex: true
          args: -pdf -file-line-error -interaction=nonstopmode -f
          continue_on_error: true
        continue-on-error: true

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
        if: always()
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: update-${{ steps.date.outputs.date }}
          RELEASE_NAME: ${{ steps.date.outputs.date }} Update

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          utcOffset: "+10:00"

      - run: |
          set -x
          assets=()
          for asset in ./*.pdf; do
            assets+=("$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          gh release create "update-${{ steps.date.outputs.date }}" "${assets[@]}" --notes "Release ${{ steps.current-time.outputs.time }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
